name: "Node.js CI"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  parameters:
    name: "Set parameters"
    runs-on: "ubuntu-latest"

  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    needs: "parameters"
    strategy:
      matrix:
        node: ["16.8"]
    steps:
      - uses: "actions/checkout@v2"
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3

      - name: "Use Node.js ${{ matrix.node }}"
        uses: "actions/setup-node@v2"
        with:
          node-version: "${{ matrix.node }}"
          cache: "pnpm"

      - name: "Install dependencies if needed"
        run: "pnpm install"

  test:
    name: "Test"
    needs: ["parameters", "build"]
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        node: ["16.8"]
    steps:
      - uses: "actions/checkout@v2"
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3

      - name: "Use Node.js ${{ matrix.node }}"
        uses: "actions/setup-node@v2"
        with:
          node-version: "${{ matrix.node }}"
          cache: "pnpm"

      - name: "Run tests"
        run: "pnpm run test"

  lint:
    name: "Lint"
    needs: ["parameters", "build"]
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        node: ["16.8"]
    steps:
      - uses: "actions/checkout@v2"
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3

      - name: "Use Node.js ${{ matrix.node }}"
        uses: "actions/setup-node@v2"
        with:
          node-version: "${{ matrix.node }}"
          cache: "pnpm"

      - name: "Run linters"
        run: "pnpm run lint"
